/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TargetsRouteImport } from './routes/targets'
import { Route as AuthenticatedAssessRouteImport } from './routes/_authenticated/assess'
import { Route as AuthenticatedCommitteeRouteImport } from './routes/_authenticated/committee'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentRouteImport } from './routes/_authenticated/document'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as ApiAssessRouteImport } from './routes/api/assess'
import { Route as ApiDemoRequestRouteImport } from './routes/api/demo-request'
import { Route as ApiPlanRouteImport } from './routes/api/plan'
import { Route as ApiProgressRouteImport } from './routes/api/progress'
import { Route as ApiReviewRouteImport } from './routes/api/review'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsRoute = TargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssessRoute = AuthenticatedAssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommitteeRoute = AuthenticatedCommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentRoute = AuthenticatedDocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAssessRoute = ApiAssessRouteImport.update({
  id: '/api/assess',
  path: '/api/assess',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoRequestRoute = ApiDemoRequestRouteImport.update({
  id: '/api/demo-request',
  path: '/api/demo-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanRoute = ApiPlanRouteImport.update({
  id: '/api/plan',
  path: '/api/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressRoute = ApiProgressRouteImport.update({
  id: '/api/progress',
  path: '/api/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewRoute = ApiReviewRouteImport.update({
  id: '/api/review',
  path: '/api/review',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/targets': typeof TargetsRoute
  '/assess': typeof AuthenticatedAssessRoute
  '/committee': typeof AuthenticatedCommitteeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/document': typeof AuthenticatedDocumentRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/review': typeof AuthenticatedReviewRoute
  '/api/assess': typeof ApiAssessRoute
  '/api/demo-request': typeof ApiDemoRequestRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/progress': typeof ApiProgressRoute
  '/api/review': typeof ApiReviewRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/targets': typeof TargetsRoute
  '/assess': typeof AuthenticatedAssessRoute
  '/committee': typeof AuthenticatedCommitteeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/document': typeof AuthenticatedDocumentRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/review': typeof AuthenticatedReviewRoute
  '/api/assess': typeof ApiAssessRoute
  '/api/demo-request': typeof ApiDemoRequestRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/progress': typeof ApiProgressRoute
  '/api/review': typeof ApiReviewRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/targets': typeof TargetsRoute
  '/_authenticated/assess': typeof AuthenticatedAssessRoute
  '/_authenticated/committee': typeof AuthenticatedCommitteeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/document': typeof AuthenticatedDocumentRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/api/assess': typeof ApiAssessRoute
  '/api/demo-request': typeof ApiDemoRequestRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/progress': typeof ApiProgressRoute
  '/api/review': typeof ApiReviewRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/targets'
    | '/assess'
    | '/committee'
    | '/dashboard'
    | '/document'
    | '/plan'
    | '/progress'
    | '/review'
    | '/api/assess'
    | '/api/demo-request'
    | '/api/plan'
    | '/api/progress'
    | '/api/review'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/targets'
    | '/assess'
    | '/committee'
    | '/dashboard'
    | '/document'
    | '/plan'
    | '/progress'
    | '/review'
    | '/api/assess'
    | '/api/demo-request'
    | '/api/plan'
    | '/api/progress'
    | '/api/review'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/targets'
    | '/_authenticated/assess'
    | '/_authenticated/committee'
    | '/_authenticated/dashboard'
    | '/_authenticated/document'
    | '/_authenticated/plan'
    | '/_authenticated/progress'
    | '/_authenticated/review'
    | '/api/assess'
    | '/api/demo-request'
    | '/api/plan'
    | '/api/progress'
    | '/api/review'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TargetsRoute: typeof TargetsRoute
  ApiAssessRoute: typeof ApiAssessRoute
  ApiDemoRequestRoute: typeof ApiDemoRequestRoute
  ApiPlanRoute: typeof ApiPlanRoute
  ApiProgressRoute: typeof ApiProgressRoute
  ApiReviewRoute: typeof ApiReviewRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets': {
      id: '/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof TargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assess': {
      id: '/_authenticated/assess'
      path: '/assess'
      fullPath: '/assess'
      preLoaderRoute: typeof AuthenticatedAssessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/committee': {
      id: '/_authenticated/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof AuthenticatedCommitteeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/document': {
      id: '/_authenticated/document'
      path: '/document'
      fullPath: '/document'
      preLoaderRoute: typeof AuthenticatedDocumentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/assess': {
      id: '/api/assess'
      path: '/api/assess'
      fullPath: '/api/assess'
      preLoaderRoute: typeof ApiAssessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo-request': {
      id: '/api/demo-request'
      path: '/api/demo-request'
      fullPath: '/api/demo-request'
      preLoaderRoute: typeof ApiDemoRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan': {
      id: '/api/plan'
      path: '/api/plan'
      fullPath: '/api/plan'
      preLoaderRoute: typeof ApiPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress': {
      id: '/api/progress'
      path: '/api/progress'
      fullPath: '/api/progress'
      preLoaderRoute: typeof ApiProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review': {
      id: '/api/review'
      path: '/api/review'
      fullPath: '/api/review'
      preLoaderRoute: typeof ApiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssessRoute: typeof AuthenticatedAssessRoute
  AuthenticatedCommitteeRoute: typeof AuthenticatedCommitteeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentRoute: typeof AuthenticatedDocumentRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssessRoute: AuthenticatedAssessRoute,
  AuthenticatedCommitteeRoute: AuthenticatedCommitteeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentRoute: AuthenticatedDocumentRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TargetsRoute: TargetsRoute,
  ApiAssessRoute: ApiAssessRoute,
  ApiDemoRequestRoute: ApiDemoRequestRoute,
  ApiPlanRoute: ApiPlanRoute,
  ApiProgressRoute: ApiProgressRoute,
  ApiReviewRoute: ApiReviewRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
