/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessRouteImport } from './routes/assess'
import { Route as DocumentRouteImport } from './routes/document'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ApiAssessRouteImport } from './routes/api/assess'
import { Route as ApiPlanRouteImport } from './routes/api/plan'
import { Route as ApiProgressRouteImport } from './routes/api/progress'
import { Route as ApiReviewRouteImport } from './routes/api/review'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessRoute = AssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentRoute = DocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessRoute = ApiAssessRouteImport.update({
  id: '/api/assess',
  path: '/api/assess',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanRoute = ApiPlanRouteImport.update({
  id: '/api/plan',
  path: '/api/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressRoute = ApiProgressRouteImport.update({
  id: '/api/progress',
  path: '/api/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewRoute = ApiReviewRouteImport.update({
  id: '/api/review',
  path: '/api/review',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/document': typeof DocumentRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/api/assess': typeof ApiAssessRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/progress': typeof ApiProgressRoute
  '/api/review': typeof ApiReviewRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/document': typeof DocumentRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/api/assess': typeof ApiAssessRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/progress': typeof ApiProgressRoute
  '/api/review': typeof ApiReviewRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/document': typeof DocumentRoute
  '/plan': typeof PlanRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/api/assess': typeof ApiAssessRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/progress': typeof ApiProgressRoute
  '/api/review': typeof ApiReviewRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assess'
    | '/document'
    | '/plan'
    | '/progress'
    | '/review'
    | '/api/assess'
    | '/api/plan'
    | '/api/progress'
    | '/api/review'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assess'
    | '/document'
    | '/plan'
    | '/progress'
    | '/review'
    | '/api/assess'
    | '/api/plan'
    | '/api/progress'
    | '/api/review'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/assess'
    | '/document'
    | '/plan'
    | '/progress'
    | '/review'
    | '/api/assess'
    | '/api/plan'
    | '/api/progress'
    | '/api/review'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessRoute: typeof AssessRoute
  DocumentRoute: typeof DocumentRoute
  PlanRoute: typeof PlanRoute
  ProgressRoute: typeof ProgressRoute
  ReviewRoute: typeof ReviewRoute
  ApiAssessRoute: typeof ApiAssessRoute
  ApiPlanRoute: typeof ApiPlanRoute
  ApiProgressRoute: typeof ApiProgressRoute
  ApiReviewRoute: typeof ApiReviewRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess': {
      id: '/assess'
      path: '/assess'
      fullPath: '/assess'
      preLoaderRoute: typeof AssessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document': {
      id: '/document'
      path: '/document'
      fullPath: '/document'
      preLoaderRoute: typeof DocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assess': {
      id: '/api/assess'
      path: '/api/assess'
      fullPath: '/api/assess'
      preLoaderRoute: typeof ApiAssessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan': {
      id: '/api/plan'
      path: '/api/plan'
      fullPath: '/api/plan'
      preLoaderRoute: typeof ApiPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress': {
      id: '/api/progress'
      path: '/api/progress'
      fullPath: '/api/progress'
      preLoaderRoute: typeof ApiProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review': {
      id: '/api/review'
      path: '/api/review'
      fullPath: '/api/review'
      preLoaderRoute: typeof ApiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessRoute: AssessRoute,
  DocumentRoute: DocumentRoute,
  PlanRoute: PlanRoute,
  ProgressRoute: ProgressRoute,
  ReviewRoute: ReviewRoute,
  ApiAssessRoute: ApiAssessRoute,
  ApiPlanRoute: ApiPlanRoute,
  ApiProgressRoute: ApiProgressRoute,
  ApiReviewRoute: ApiReviewRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
